services:
  - type: web
    name: opengym
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DATA_DIR
        value: ./data
      - key: RP_ID
        sync: false
      - key: ORIGIN
        sync: false
      - key: RP_NAME
        value: openGym
